### PR TITLE
Check if raw mode is supported before enabling

### PR DESCRIPTION
**Pull request by mAAdhaTTah**
This will otherwise throw if raw mode is not supported before
turning it on.

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
I verified locally that this change alone, without the testing library change, fixes my snapshot tests. Adding the testing library change on top gets the i/o tests working as well.

**Comment by vadimdemedes** [comment]
I think that's something that developer should control, as most likely you'll want to fallback to a different output. Having this component check if raw mode is supported and not doing anything could cause confusion.

I'm thinking about renaming `isRawModeSupported` to `isUserInputSupported`, because I imagine not everyone knows what is raw mode about.

**Comment by vadimdemedes** [comment]
Opened https://github.com/vadimdemedes/ink/issues/203 to track this idea.

**Comment by mAAdhaTTah** [comment]
How would the developer control it within this library?

**Comment by vadimdemedes** [comment]
You'd have to do something like this:

```jsx
<StdinContext.Consumer>
	{({ isRawModeSupported }) => (
		<Box>
			{isRawModeSupported && <TextInput/>}
		</Box>
	)}
</StdinContext.Consumer>
```

**Pull request closed without merging**
