### PR TITLE
Add optional readline functionality to component

### PR DESCRIPTION
**Pull request by sekistner**
I don't know if this is a perfect solution, also the text is then at the bottom, but not being able to paste is a real problem.

The cli is most likely to fast for node to react on every keypress event during a paste, it suddenly worked when I had a console log in between.

### CODE REVIEW

**Comment by vadimdemedes** [comment]
> also the text is then at the bottom

How come?

Your solution is interesting, maybe it's something that Ink should support out-of-the-box, since basically every input needs to support pasting.

**Comment by sekistner** [comment]
> How come?

I assume it's part of the native implementation, don't know for sure. I just tried to find a solution for the problem and stumbled over readline.

I assume the readline implementation inside node is there because pasting is for the terminal a fast succession of keystrokes and they need to be buffered.

**Comment by jimthedev** [comment]
Any chance of this making it in?

**Comment by jimthedev** [comment]
And to be clear I am really just interested in paste functionality. If this gets it there then great.

**Comment by vadimdemedes** [comment]
Ideally I want to have this in the Ink itself, so that anyone can benefit. I'm really short on time lately, so I can't give any ETAs yet.

**Comment by jimthedev** [comment]
If you are open to it I could see if we could get it into ink itself?

**Comment by vadimdemedes** [comment]
Sure, feel free to experiment with it.

**Pull request closed without merging**
